- name: set variable
  set_fact:
    consul_token: "{{ lookup('env', 'consul_master_token') }}"

- name: Check if intention nifi => nifi-registry (allow) exists
  shell: consul intention match -source nifi
  register: nifi_intention
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny'
  environment:
    CONSUL_HTTP_ADDR: "{{ lookup('env', 'CONSUL_HTTP_ADDR') }}"
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"


- name: Consul create intention nifi => nifi-registry (allow)
  shell: consul intention create nifi nifi-registry
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny' and nifi_intention.stdout_lines == []
  environment:
    CONSUL_HTTP_ADDR: "{{ lookup('env', 'CONSUL_HTTP_ADDR') }}"
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"

- name: Check if intention nifi-local => nifi (allow) exists
  shell: consul intention match -source nifi-local
  register: nifi_local_intention
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny'
  environment:
    CONSUL_HTTP_ADDR: "{{ lookup('env', 'CONSUL_HTTP_ADDR') }}"
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"

- name: Consul create intention nifi-local => nifi (allow)
  shell: consul intention create nifi-local nifi
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny' and nifi_local_intention.stdout_lines == []
  environment:
    CONSUL_HTTP_ADDR: "{{ lookup('env', 'CONSUL_HTTP_ADDR') }}"
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"