- name: set variable
  set_fact:
    consul_token: "{{ lookup('env', 'consul_master_token') }}"

- name: Check if intention nifi_registry => nifi (allow) exists
  shell: consul intention match -source nifi_registry
  register: nifi_registry_intention
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny'
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"

- name: Consul create intention nifi_registry => nifi (allow)
  shell: consul intention create nifi_registry  nifi
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny' and nifi_registry_intention.stdout_lines == []
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"

- name: Check if intention nifi-local => nifi (allow) exists
  shell: consul intention match -source nifi-local
  register: nifi_local_intention
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny'
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"

- name: Consul create intention nifi-local => nifi (allow)
  shell: consul intention create nifi-local nifi
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny' and nifi_local_intention.stdout_lines == []
  environment:
    CONSUL_HTTP_TOKEN: "{{ consul_token }}"