- name: Terraform nifi
  terraform:
    project_path: ../../example/{{ mode }}
    force_init: true
    state: present
  register: terraform

- name: Terraform stdout
  debug:
    msg: "{{terraform.stdout}}"